#!/bin/bash
# Define the variables needed by your virtual machine Char in the general env of your terminal, so that you can run the docker ps command without errors. You have to fix all four environment varibles with one command, and you are not allowed to use your shell’s builtin to set these variables by hand.
# Essentially, you can't run it through shell, you'll have to manually copy and paste it into terminal

eval "$(docker-machine env dev)"
